spring:
  application:
    name: cmm-ms-matricula-service
  datasource:
    url: jdbc:h2:mem:matricula  # BD en memoria llamada "cliente"
    driver-class-name: org.h2.Driver
    username: sa
    password:
  jpa:
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.H2Dialect

  h2:
    console:
      enabled: true
      path: /h2-console  # consola accesible en http://localhost:6263/h2-console

server:
  port: 6263

springdoc:
  api-docs:
    enabled: true
  swagger-ui:
    enabled: true
    path: /doc/swagger-ui.html

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8092/eureka
  instance:
    hostname: localhost