server:
  port: 5050

spring:
  application:
    name: cmm-ms-config-server

  cloud:
    config:
      server:
        git:
          uri: https://github.com/Cristian-Mamani/cmm-examen-dad.git
          searchPaths:
            - cmm-config-data
          default-label: main

  security:
    user:
      name: root
      password: 123456
